var list = [
  "NIL",
  "Others",
  "Analgesics",
  "Paracetamol",
  "Ibuprofen",
  "Co-codamol (paracetamol and codeine mix)",
  "Codeine",
  "Tramadol",
  "Morphine",
  "Diclofenac",
  "Asprin",
  "Naproxen",
  "Dihydrocodeine",
  "Oxycodone",
  "Nefopam",
  "Gabapentin",
  "Fentanyl",
  "Ketamine",
  "Antiarrhythmics",
  "Bisoprolol",
  "Atenolol",
  "Digoxin",
  "Amiodarone",
  "Adenosine",
  "Diltiazem",
  "Antibiotics",
  "Amoxicillin",
  "Flucloxacillin",
  "Meropenem",
  "Vancomycin",
  "Gentamycin",
  "Clarithromycin",
  "Co-amoxiclav",
  "Doxycycline",
  "Ceftazidime",
  "Piperacillin / Tazobactam (tazocin)",
  "Ciprofloxacin",
  "Levofloxacin",
  "Cephalexin",
  "Cefuroxime",
  "Clindamycin",
  "Trimethoprim",
  "Nitrofurantoin",
  "Anticoagulants",
  "Warfarin",
  "Rivaroxaban",
  "Apixaban",
  "Enoxaparin",
  "Funderparinex",
  "Heparin",
  "Anticonvulsants",
  "Sodium valproate (Epilim)",
  "Phenytoin",
  "Levetiracetam (Keppra)",
  "Gabapentin",
  "Clonazepam",
  "Diazapam",
  "Lorazepam",
  "Carbamazepine",
  "Antidepressants",
  "Citalopram",
  "Fluoxetine",
  "Amitriptyline",
  "Sertraline",
  "Venlafaxine",
  "Mirtazapine",
  "Trazodone",
  "Antiemetics",
  "Cyclizine",
  "Ondansetron",
  "Metoclopramide",
  "Prochlorperazine",
  "Levomepromazine",
  "Antihypertensives",
  "Ramipril",
  "Doxazosin",
  "Candesartan",
  "Losartan",
  "Lisinopril",
  "Atenolol",
  "Bisoprolol",
  "Amlodipine",
  "Diltiazem",
  "Nifedipine",
  "Antihyperglycemics",
  "Metformin",
  "Insulin",
  "Gliclazide",
  "Bronchodilators",
  "Salbutamol",
  "Ipratropium",
  "Tiotropium",
  "Theophylline",
  "Diuretics",
  "Furosemide",
  "Bumetanide",
  "Spironolactone",
  "Bendroflumethiazide",
  "Indapamide",
  "Amiloride",
  "Intravenous Fluids",
  "Normal Saline",
  "Plasmalyte",
  "Hartmann’s solution",
  "Geloplasma / Plasmalyte",
  "Glucose",
  "Sedatives",
  "Zopiclone",
  "Haloperidol",
  "Lorazepam",
  "Midazolam",
  "Diazepam",
  "Chlordiazepoxide",
  "Temazepam",
  "Phenobarbitol",
  "Statins",
  "Simvastatin",
  "Atorvastatin",
  "Pravastatin",
  "Supplements",
  "Levothyroxine",
  "Adcal / Calcichew",
  "Ferrous Fumarate",
  "Ferrous Sulphate",
  "Multivitamins",
  "Thiamine",
  "Cholecalciferol",
  "Quinine",
  "Folic Acid",
  "Sandoz-K",
  "Sandoz-Phosphate",
  "Slow sodium",
  "Alendronic Acid",
  "Laxatives",
  "Lactulose",
  "Senna",
  "Movicol",
  "Sodium Docusate",
  "Bisacodyl",
  "Phosphate Enema",
  "Microlax Enema",
  "Glycerine Suppositories",
  "Proton Pump Inhibitors",
  "Omeprazole",
  "Lansoprazole",
  "Esomeprazole",
  "Ranitidine (H2-receptor-blocker)",
  "Peptac",
];
