var list = [
  "Others",
  "NIL",
  "Fever",
  "Cough",
  "Flu-like symptoms",
  "Runny nose",
  "Sneezing",
  "SoreThroat",
  "Nauseau",
  "Vomitting",
  "Dizziness",
  "General body ache",
  "Body weakness",
  "Fatigue",
  "Numbness",
  "Mood swings",
  "Depression",
  "Anxiety",
  "Breathlessness",
  "Vertigo",
  "Poor appetite",
  "Increased appetite",
  "Difficulty concentrating",
  "Confusion",
  "Memory loss",
  "Diarrhea",
  "Gastric",
  "Nosebleed"
];
